import {initializeApp} from "https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
import {getFirestore,collection,addDoc,query,orderBy,getDocs,deleteDoc,doc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
$("loginBtn").onclick=async()=>{ $("loginMsg").textContent="Signing in...";try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);$("loginMsg").textContent="";}catch(e){$("loginMsg").textContent="Login failed: "+e.message;}};
$("logoutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(u){$("loginCard").classList.add("hidden");$("panel").classList.remove("hidden");await load();}else{$("loginCard").classList.remove("hidden");$("panel").classList.add("hidden");}});
$("noticeForm").onsubmit=async e=>{e.preventDefault();$("publishMsg").textContent="Publishing...";try{await addDoc(collection(db,"notices"),{title:$("title").value.trim(),date:$("date").value,category:$("category").value,details:$("details").value.trim(),pdfUrl:$("pdfUrl").value.trim(),publishedAt:serverTimestamp()});$("publishMsg").textContent="Notice published successfully.";e.target.reset();await load();}catch(err){$("publishMsg").textContent="Publish failed: "+err.message;}};
async function load(){let box=$("noticeList");box.textContent="Loading...";try{let s=await getDocs(query(collection(db,"notices"),orderBy("publishedAt","desc")));if(s.empty){box.textContent="No notices published yet.";return;}box.innerHTML="";s.forEach(x=>{let n=x.data(),d=document.createElement("div");d.className="notice";d.innerHTML="<strong>"+esc(n.title)+"</strong><br><small>"+esc(n.date||"")+" • "+esc(n.category||"Notice")+"</small><p>"+esc(n.details||"")+"</p>"+(n.pdfUrl?'<a href="'+esc(n.pdfUrl)+'" target="_blank" rel="noopener">Open document</a><br>':"")+'<button class="danger">Delete</button>';d.querySelector("button").onclick=async()=>{if(confirm("Delete this notice?")){await deleteDoc(doc(db,"notices",x.id));load();}};box.appendChild(d);});}catch(e){box.textContent="Could not load notices: "+e.message;}}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
